from __future__ import annotations

DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_WORKERS = 1
DEFAULT_TABLE_STRATEGY = "lines_strict"
FALLBACK_TABLE_STRATEGIES = ("lines", "text")
TEXT_LAYER_MIN_WORDS = 5
TEXT_LAYER_MIN_CHARS = 20
TEXT_LAYER_MIN_WORDS_PER_PAGE = 1.0
TEXT_LAYER_MIN_CHARS_PER_PAGE = 8.0
IMAGE_CAPTION_LEFT_TOLERANCE_RATIO = 0.12
IMAGE_CAPTION_VERTICAL_GAP_RATIO = 0.06
OUTPUT_SCOPE = "digital-pdf-only"
GENERATOR_VERSION = "phase2-v1"
